name: Terraform Plan

on:
  push:
    branches:
      - main
    pull_request:
    
permissions:
      id-token: write
      contents: read
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
      ARM_CLIENT_SCRETE: ${{secrets.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARM_TENENT_ID: ${{secrets.TENANT_ID}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install jq -y
      
      - name: Parse JSON
        run: chmod +x sample.sh | ./sample.sh

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
          ARM_CLIENT_SCRETE: ${{secrets.CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
          ARM_TENENT_ID: ${{secrets.TENANT_ID}}
        run: terraform -chdir=./config init



        
